const experience = [
  {
    id: 0,
    company: "FreeCharge-Axis Bank",
    profile: "Graduate Engineer Trainee",
    tasks: [
      " * Contributed to Subzero Migration & design change of all the existing products in Supernova according to new design storybook.",
      " * Contributed to working on active sprint tasks & changes in Merchant Finance Product.",
      "* Contributed to reducing technical debt throughout Merchant Finance Product.",
      "* Created the DBAT-Dashboard from the ground-up to be used as internal tool for fetching information about employees/services/projects and other information.",
      "* Acquired hands-on expertise in Agile/Scrum methodologies, gaining a deep understanding of Agile principles.",
      "* Got hands on experience with front-end technologies including HTML, CSS, Javascript, and ReactJS, Redux, Material-UI",
      "* Enhanced development skills, debugging skills, utilised technical documentation",
      "* Experienced strong teamwork, effective collaboration and communication with cross-functional teams.",
      "* Familiarity in CI/CD pipelines and tools (Jenkins, GitLab CI/CD).",
    ],
    duration: "June,2023-April,2024",
    src: "/assests/freecharge.png",
  },
  {
    id: 0,
    company: "FreeCharge-Axis Bank",
    profile: "Software Developer",
    tasks: [
      " * Contributed to Subzero Migration & design change of all the existing products in Supernova according to new design storybook.",
      " * Contributed to working on active sprint tasks & changes in Merchant Finance Product.",
      "* Contributed to reducing technical debt throughout Merchant Finance Product.",
      "* Created the DBAT-Dashboard from the ground-up to be used as internal tool for fetching information about employees/services/projects and other information.",
      "* Acquired hands-on expertise in Agile/Scrum methodologies, gaining a deep understanding of Agile principles.",
      "* Got hands on experience with front-end technologies including HTML, CSS, Javascript, and ReactJS, Redux, Material-UI",
      "* Enhanced development skills, debugging skills, utilised technical documentation",
      "* Experienced strong teamwork, effective collaboration and communication with cross-functional teams.",
      "* Familiarity in CI/CD pipelines and tools (Jenkins, GitLab CI/CD).",
    ],
    duration: "April,2024-present",
    src: "/assests/freecharge.png",
  },
  {
    id: 0,
    company: "Microsoft",
    profile: "Sweeper",
    tasks: [
      " * Contributed to Subzero Migration & design change of all the existing products in Supernova according to new design storybook.",
      " * Contributed to working on active sprint tasks & changes in Merchant Finance Product.",
      "* Contributed to reducing technical debt throughout Merchant Finance Product.",
      "* Created the DBAT-Dashboard from the ground-up to be used as internal tool for fetching information about employees/services/projects and other information.",
      "* Acquired hands-on expertise in Agile/Scrum methodologies, gaining a deep understanding of Agile principles.",
      "* Got hands on experience with front-end technologies including HTML, CSS, Javascript, and ReactJS, Redux, Material-UI",
      "* Enhanced development skills, debugging skills, utilised technical documentation",
      "* Experienced strong teamwork, effective collaboration and communication with cross-functional teams.",
      "* Familiarity in CI/CD pipelines and tools (Jenkins, GitLab CI/CD).",
    ],
    duration: "April,2024-present",
    src: "/assests/freecharge.png",
  },
  {
    id: 0,
    company: "Godlman Sachs",
    profile: "Dishwasher",
    tasks: [
      " * Contributed to Subzero Migration & design change of all the existing products in Supernova according to new design storybook.",
      " * Contributed to working on active sprint tasks & changes in Merchant Finance Product.",
      "* Contributed to reducing technical debt throughout Merchant Finance Product.",
      "* Created the DBAT-Dashboard from the ground-up to be used as internal tool for fetching information about employees/services/projects and other information.",
      "* Acquired hands-on expertise in Agile/Scrum methodologies, gaining a deep understanding of Agile principles.",
      "* Got hands on experience with front-end technologies including HTML, CSS, Javascript, and ReactJS, Redux, Material-UI",
      "* Enhanced development skills, debugging skills, utilised technical documentation",
      "* Experienced strong teamwork, effective collaboration and communication with cross-functional teams.",
      "* Familiarity in CI/CD pipelines and tools (Jenkins, GitLab CI/CD).",
    ],
    duration: "April,2024-present",
    src: "/assests/freecharge.png",
  },
];

export default experience;
