const projects = [
  {
    id: 0,
    title: "Portfolio",
    desc: "A personalized React portfolio showcasing skills, experience, and projects, styled with Material UI. Integrates themes and other functionalities of React for enhanced user experience.",
    techStack: ["ReactJS", "Material-UI", "Javascript"],
    url: "/assests/portfolio.jpg",
    link: "https://react-portfolio-pink-two.vercel.app/",
  },
  {
    id: 1,
    title: "Book Store",
    desc: "A MERN app styled with Tailwind CSS and cloud MongoDb database, featuring a book store e-commerce platform with authentication and login functionalities for seamless user experience.",
    techStack: ["React", "TailWind", "NodeJs", "MongoDB", "Express"],
    url: "/assests/bookstore.jpg",
    link: "https://book-store-pi-beryl.vercel.app/",
  },
  {
    id: 2,
    title: "Calculator",
    desc: "Interactive calculator built with JavaScript, featuring a user-friendly design and core mathematical functions.",
    techStack: ["HTML", "CSS", "Javascript"],
    url: "/assests/calculator.jpg",
    link: "https://aryanj57.github.io/Calculator-Basic-/",
  },
  {
    id: 3,
    title: "Ecommerce",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non corporis ipsum nostrum libero placeat nam impedit voluptas ducimus nesciunt delectus!",
    techStack: ["HTML", "CSS", "Javascript"],
    url: "/assests/ecommerce.jpg",
    link: "https://aryanj57.github.io/e_commerce_website/",
  },
  {
    id: 4,
    title: "Goals Tracker",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non corporis ipsum nostrum libero placeat nam impedit voluptas ducimus nesciunt delectus!",
    techStack: ["HTML", "CSS", "Javascript"],
    url: "/assests/goalsTracker.jpg",
    link: "https://aryanj57.github.io/Daily-goals/",
  },
  {
    id: 5,
    title: "Weather App",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non corporis ipsum nostrum libero placeat nam impedit voluptas ducimus nesciunt delectus!",
    techStack: ["HTML", "CSS", "Javascript"],
    url: "/assests/weatherApp.jpg",
    link: "https://aryanj57.github.io/Weather-App/",
  },
  {
    id: 6,
    title: "Social Media",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non corporis ipsum nostrum libero placeat nam impedit voluptas ducimus nesciunt delectus!",
    techStack: ["HTML", "CSS", "Javascript"],
    url: "/assests/socialMedia.jpg",
    link: "https://aryanj57.github.io/Social_Media_Profile_Page/",
  },
];

export default projects;
